server:
  port: 8082
spring:
  application:
    name: consumer-service
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
gray:
  enable: true