server:
  port: 8090
spring:
  application:
    name: zuul
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    user:
      path: /consumer/**
      serviceId: consumer-service
    order:
      path: /provider/**
      service-id: provider-service
logging:
  level:
    com.github.dingey.swagger: debug
gray:
  enable: true