server:
  port: 8761
spring:
  application:
    name: registry
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
swagger:
  all: true